StudentManagerProject.Web/Models/Course.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentManagerProject.Web.Models
{
    public class Course
    {
        public Guid Id { get; set; }
        public string UniqueIdentifyer { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public Guid SubjectId { get; set; }
        [ForeignKey("SubjectId")]
        public Subject Subject { get; set; } = default!;
        public string? Summary { get; set; }
        public bool Published { get; set; }
        public DateTime DatePublished { get; set; }

        public List<Tutor>? Tutors { get; set; }
        public List<CourseSubTopic>? Chapters { get; set; }
        public List<CourseActivity>? Activities { get; set; }
    }
}

StudentManagerProject.Web/Components/SubjectsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagerProject.Web.Repository;

namespace StudentManagerProject.Web.Components
{
    public class SubjectsViewComponent : ViewComponent
    {
        private readonly ISubjectRepository _repo;
        public SubjectsViewComponent(ISubjectRepository repo)
        {
            _repo = repo;
        }

        public IViewComponentResult Invoke() 
        {
            var subjectList = _repo.GetAll();
            return View(subjectList);
        }
    }
}

StudentManagerProject.Web/Pages/Courses.cshtml.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StudentManagerProject.Web.Models;
using StudentManagerProject.Web.Repository;

namespace StudentManagerProject.Web.Pages
{
    public class CoursesModel : PageModel
    {
        public IEnumerable<Course> courses = new List<Course>();
        
        private readonly ICourseRepository courseRepository;

        public CoursesModel(ICourseRepository repo)
        {
            courseRepository = repo;
        }

        public void OnGet(string queryString)
        {
            courses = courseRepository.GelAllCourses();
        }
    }
}

StudentManagerProject.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StudentManagerProject.Web.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

StudentManagerProject.Web/Pages/Courses.cshtml
@page
@model CoursesModel
@{
    ViewBag.Title = "All Published Courses";
}

<div class="courses-banner">
    <div class="container p-5">
        <div class="row">
            <div class="col-lg-9 col-sm-12">
                <h1>Browse all published courses</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row m-5">
        <div class="col-lg-9 col-sm-12">
            @if(Model.courses.Count() > 0)
            {
                foreach (var course in Model.courses)
                {
                     <partial name="_SinglePartial" model="course" />
                }
            }
            else
            {
                <h3 class="text-center text-warning">Sorry! there are no courses to be displayed at this time</h3>
            }
        </div>

        <div class="col-lg-2 offset-1">
            @Component.InvokeAsync("Subjects").Result
        </div>
    </div>
</div>

StudentManagerProject.Web/Pages/Index.cshtml
@page
@model StudentManagerProject.Web.Pages.IndexModel

@{
    ViewBag.Title = "Welcome Page";
}

<div class="main-banner">
    <div class="container">
        <div class="col-6 offset-3 p-5">
            <h1 class="main-title">Student Management System</h1>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card">
                <img style="height:200px" src="https://images.pexels.com/photos/5537517/pexels-photo-5537517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="student">
                <div class="card-body">
                    <h5 class="card-title">Visit Student Portal</h5>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <a href="#" class="btn btn-primary">Proceed</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img style="height:200px" src="https://images.pexels.com/photos/5905559/pexels-photo-5905559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="courses">
                <div class="card-body">
                    <h5 class="card-title">Browse online courses</h5>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <a asp-page="/Courses" class="btn btn-primary">Proceed</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img style="height:200px" src="https://images.pexels.com/photos/7079/people-woman-girl-writing.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="tutor">
                <div class="card-body">
                    <h5 class="card-title">Visit Tutor Portal</h5>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Proceed</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img style="height:200px" src="https://images.pexels.com/photos/5537517/pexels-photo-5537517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <a href="#" class="btn btn-primary">Proceed</a>
                </div>
            </div>
        </div>
    </div>
</div>